package one.monero.moneroone.core.wallet

import io.horizontalsystems.monerokit.CakeWalletStyleConverter
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/** Pure (non-native) parts of SeedValidation. */
class SeedValidationTest {

    // Known-good BIP39 seed generated by the app on the emulator run; the
    // converter yields a checksum-valid 25-word English Electrum seed for it.
    private val bip39 = ("blind ginger glare shrimp copper farm useless pluck task disease this laugh " +
        "build frog prison inner heavy delay scissors order eager treat youth genre").split(" ")

    private fun validElectrum(): List<String> {
        val words = CakeWalletStyleConverter.getLegacySeedFromBip39(bip39, "")
        assertNotNull(words)
        assertEquals(25, words!!.size)
        return words
    }

    @Test
    fun `converter output passes the electrum checksum rule`() {
        assertNull(SeedValidation.electrumSeedProblem(validElectrum()))
    }

    @Test
    fun `swapping one word breaks the checksum`() {
        val words = validElectrum().toMutableList()
        // Replace word 5 with a different dictionary word (avoid the checksum word itself).
        val replacement = CakeWalletStyleConverter.MONERO_WORDLIST.first { it != words[4] && it != words[24] }
        words[4] = replacement
        assertNotNull(SeedValidation.electrumSeedProblem(words))
    }

    @Test
    fun `wrong checksum word is rejected`() {
        val words = validElectrum().toMutableList()
        words[24] = CakeWalletStyleConverter.MONERO_WORDLIST.first { it !in words.take(24) }
        assertEquals("checksum word mismatch", SeedValidation.electrumSeedProblem(words))
    }

    @Test
    fun `unknown word and wrong count are rejected`() {
        val words = validElectrum().toMutableList()
        words[0] = "notaword"
        assertEquals("word not in wordlist", SeedValidation.electrumSeedProblem(words))
        assertNotNull(SeedValidation.electrumSeedProblem(validElectrum().take(24)))
    }

    @Test
    fun `same word 25 times passes the checksum rule - null-key guard must catch it`() {
        // "abbey" x25 is checksum-valid (every candidate checksum word is "abbey"),
        // yet derives a null spend key. The rule is not the last line of defense.
        val words = List(25) { "abbey" }
        assertNull(SeedValidation.electrumSeedProblem(words))
        assertTrue(SeedValidation.isEnglishElectrum(words))
    }

    @Test
    fun `null and malformed keys are detected`() {
        assertTrue(SeedValidation.isNullKey(null))
        assertTrue(SeedValidation.isNullKey(""))
        assertTrue(SeedValidation.isNullKey("0".repeat(64)))
        assertTrue(SeedValidation.isNullKey("zz".repeat(32)))
        assertTrue(SeedValidation.isNullKey("ab".repeat(31)))
        assertFalse(SeedValidation.isNullKey("ab".repeat(32)))
        assertFalse(SeedValidation.isNullKey("0".repeat(63) + "1"))
    }

    @Test
    fun `null-key burn address is rejected, real address accepted`() {
        val nullKey = "41fJjQDhryD11111111111111111111111111111111112N1GuTZeagfRbbKcALdcZev4QXGGuoLh2x36LhaxLSxCc2YDhi"
        val real = "494docVv9psYhYnqqDjbemaz3veCWczoUKfwiELFQ36W4TXdSg7RroeBvTxKagSdt1BYhne62ESAzT7H2TqVTkrJ7m1pCoE"
        assertEquals(95, nullKey.length)
        assertEquals(95, real.length)
        assertFalse(SeedValidation.isPlausiblePrimaryAddress(nullKey))
        assertTrue(SeedValidation.isPlausiblePrimaryAddress(real))
        assertFalse(SeedValidation.isPlausiblePrimaryAddress(null))
        assertFalse(SeedValidation.isPlausiblePrimaryAddress(""))
        assertFalse(SeedValidation.isPlausiblePrimaryAddress(real.drop(1)))          // 94 chars
        assertFalse(SeedValidation.isPlausiblePrimaryAddress("8" + real.drop(1)))    // subaddress prefix
        assertFalse(SeedValidation.isPlausiblePrimaryAddress(real.replace('4', '0'))) // non-base58
    }

    @Test
    fun `cache base name strips the unportable marker`() {
        assertEquals("c4d72b4f19457914877dd76e4e355ecf", WalletCacheIds.cacheBaseName("c4d72b4f19457914877dd76e4e355ecf.unportable"))
        val orphans = WalletCacheIds.orphanedCacheBaseNames(
            entries = listOf("deadbeefdeadbeefdeadbeefdeadbeef.unportable", "deadbeefdeadbeefdeadbeefdeadbeef.keys"),
            knownIds = setOf("c4d72b4f19457914877dd76e4e355ecf"),
            allWalletIdsKnown = true
        )
        assertEquals(listOf("deadbeefdeadbeefdeadbeefdeadbeef"), orphans)
    }
}
